IISportSchool/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IISportSchool.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace IISportSchool.Controllers
{
    [Authorize(Roles = DefaultRoles.Admin)]
    public class InfoController : Controller
    {
        ApplicationDbContext _context;
        List<SchoolService> services = new List<SchoolService>();
        List<Children> Childrens = new List<Children>();
        List<Worker> Workers = new List<Worker>();
        double Salaries = 0;
        double Profit = 0;
        InfoViewModel viewModel;
        public InfoController(ApplicationDbContext context)
        {
            _context = context;
            services.AddRange(_context.Departments
                .Include(s => s.Sections)
                    .ThenInclude(se => se.Groups)
                        .ThenInclude(g=>g.Childrens)
                .Include(s=>s.Sections)
                    .ThenInclude(se=>se.Teachers)
                    .ThenInclude(t=>t.Position)
                .ToList());
            foreach (var service in services)
            {
                Workers.AddRange(service.GetStaff());
                Childrens.AddRange(service.GetAllChildren());
                Profit += service.GetServiceProfit();
            }
            foreach (var worker in Workers)
                Salaries += worker.Salary;
        }
        public IActionResult Index()
        {
            viewModel = new InfoViewModel
            {
                Childrens = Childrens,
                Workers = Workers,
                Profit = Profit,
                Salaries = Salaries
            };
            return View(viewModel);
        }
    }

}

IISportSchool/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IISportSchool.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using IISportSchool.Models.FluentValidators;
using System.IO;
using Microsoft.AspNetCore.Authorization;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace IISportSchool.Controllers
{
    public class ServiceController : Controller
    {
        AbstractDepartmentDeleter _deleter;
        IServiceRepository _services;
        public ServiceController(AbstractDepartmentDeleter deleter, IServiceRepository service)
        {
            _deleter = deleter;
            _services = service;
        }
        // GET: /<controller>/
        public IActionResult DepartmentList()
        {
            var dep = _services.Departments.Include(d => d.Sections).ToList();
            return View(dep);
        }
        public IActionResult DepartmentDetails(int? id)
        {
            if (id == null || id == 0)
                return BadRequest();

            var department = _services.GetDepartment((int)id);

            if (department == null)
                return NotFound();

            return View(department);
        }

        [HttpGet]
        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult AddDepartment()
        {
            Department department = new Department { ImagePath = @"~/images/departmentLogos/" };
            return View(department);
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddDepartment(Department department)
        {
            if (!ModelState.IsValid)
            {
                return View(department);
            }
            if (department == null)
                return BadRequest();
            _services.CreateDepartment(department);
            _services.Save();

            return RedirectToAction("DepartmentList");
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult UpdateDepartment(int? id)
        {
            if (id == null || id == 0)
                return BadRequest();

            var department = _services.GetDepartment((int)id);

            if (department == null)
                return NotFound();

            return View(department);
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpPost]
        public IActionResult UpdateDepartment(Department department)
        {
            if (!ModelState.IsValid)
            {
                return View(department);
            }

            _services.UpdateDepartment(department);
            _services.Save();
            return RedirectToAction("DepartmentList");
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult DeleteDepartment(int? id)
        {
            if (id == null || id == 0)
                return BadRequest();

            var department = _services.Departments.SingleOrDefault(d => d.Id == id);

            if (department == null)
                return NotFound();

            return View(department);
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult DeleteDepartmentConfirmed(int Id)
        {
            _deleter.DeleteDepartment(Id);

            return RedirectToAction("DepartmentList");
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult AddSection(int departmentId = 0)
        {
            Section section = new Section
            {
                DepartmentId = departmentId,
                ImagePath = @"~/images/sections/"
            };
            ViewBag.Department = _services.GetDepartment(departmentId);
            //ViewBag.Departments = new SelectList(_context.Departments, "Id", "Name");
            return View(section);
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddSection(Section section)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Department = _services.GetDepartment(section.DepartmentId);
                return View(section);
            }
            if (section == null)
                return BadRequest();

            _services.CreateSection(section);
            _services.Save();
            return RedirectToAction("DepartmentList");
        }

        public IActionResult SectionDetails(int? id)
        {
            if (id == null)
                return BadRequest();

            var section = _services.GetSection((int)id);

            if (section == null)
                return NotFound();

            return View(section);
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult DeleteSection(int? id)
        {
            if (id == null)
                return BadRequest();

            var section = _services.ListOfSections()
                .Include(s => s.Department)
                .SingleOrDefault(s => s.Id == id);

            if (section == null)
                return NotFound();

            return View(section);
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult DeleteSectionConfirmed(int? id)
        {
            var section = _services.ListOfSections()
                .Include(s => s.Department)
                .SingleOrDefault(s => s.Id == id);

            if(section != null)
            {
                _services.DeleteSection(section);
                _services.Save();
            }

            return RedirectToAction("DepartmentList");
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult UpdateSection(int? id)
        {
            if (id == 0 || id == null)
                return BadRequest();

            var section = _services.GetSectionWithGroups((int)id);

            if (section == null)
                return NotFound();

            if (string.IsNullOrEmpty(section.ImagePath))
                section.ImagePath = @"images\sections\";

            return View(section);
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpPost]
        public IActionResult UpdateSection(Section section)
        {
            _services.UpdateSection(section);
            _services.Save();
            return RedirectToAction("DepartmentList");
        }
    }
}

IISportSchool/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using IISportSchool.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace IISportSchool.Controllers
{
    public class TeacherController : Controller
    {
        private ITeacherRepository _repository;
        private IServiceRepository _schoolServices;
        private IPositionFactory _positionFactory;
        private IGroupRepository _groupRepository;
        private TeacherFactory _factory;
        private TeacherProxyFactory _proxyFactory;

        private IHostingEnvironment _hostingEnviroment;

        public TeacherController(ITeacherRepository repository, IServiceRepository serviceRepository,
            IPositionRepository positionRepository, ApplicationDbContext context,
            IGroupRepository groupRepository, IHostingEnvironment hostingEnviroment)
        {
            _repository = repository;
            _schoolServices = serviceRepository;
            _groupRepository = groupRepository;
            _hostingEnviroment = hostingEnviroment;
            _proxyFactory = new TeacherProxyFactory(context);
            _positionFactory = new PositionFactory(positionRepository);
            _factory = new TeacherFactory(context, _positionFactory);
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            List<TeacherProxy> proxies = new List<TeacherProxy>();
            foreach (var teacher in _repository.Teachers)
                proxies.Add(_proxyFactory.Get(teacher.Id));
            return View(proxies);
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpGet]
        public IActionResult Create()
        {
            TeacherViewModel viewModel = new TeacherViewModel();
            viewModel.Sections = _schoolServices.ListOfSections().ToList();
            return View(viewModel);
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpPost]
        public IActionResult Create(TeacherViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Sections = _schoolServices.ListOfSections().ToList();
                return View(viewModel);
            }
                

            string uniqueFileName = null;
            if(viewModel.Photo != null)
            {
                string uploadsFolder = Path.Combine(_hostingEnviroment.WebRootPath, "images", "teachers");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + viewModel.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                viewModel.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
            }
            IPositionStrategy strategy = new PositionStrategy();
            string name = strategy.CreatePosition(viewModel.SectionId);
            var sectionName = _schoolServices.GetSection((int)viewModel.SectionId).Name;
            Teacher teacher = _factory.Create(viewModel);
            Position position = _positionFactory.GetPosition(name);
            teacher.Position = position;
            teacher.PhotoPath = uniqueFileName;
            _repository.Add(teacher);
            return RedirectToAction("Index");
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
                return BadRequest();

            var teacher = _repository.GetTeacher((int)id);
            if (teacher == null)
                return NotFound();

            UpdateteacherViewModel teacherViewModel = _factory.UpdateViewModel(teacher);
            return View(teacherViewModel);
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpPost]
        public IActionResult Update(UpdateteacherViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            _repository.Update(viewModel);
            return RedirectToAction("Index");
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult Delete(Teacher teacher)
        {
            _repository.Delete(teacher);
            return RedirectToAction("Index");
        }
    }
}

IISportSchool/Views/Shared/_DepartmentCard.cshtml
@model Department

<div class="card card1">
    <img class="img-fluid img-max-250" src="@Url.Content(@Model.ImagePath)"/>
    <hr/>
    <div class="card-body">
        <div class="card-title text-center font-weight-bold">@Model.Name</div>
    </div>
    <a class="stretched-link" asp-action="DepartmentDetails" asp-controller="Service" asp-route-id="@Model.Id"></a>
</div>

IISportSchool/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/ValidationErrors.css" rel="stylesheet" />
    <link href="~/css/DownDiv.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
</head>
<body>
        <header>
            @Html.Partial("_NavBar")
        </header>

        <main>
            <div>
                @RenderBody()
            </div>
        </main>   
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: true);
    }
</body>
</html>

IISportSchool/Views/Shared/_NavBar.cshtml
@inject SignInManager<IdentityUser> signInManager;

<div class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="navbar-header">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">Спортшкола</a>
    </div>

    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">

            <li class="nav-item">
                <a class="nav-link" asp-action="DepartmentList" asp-controller="Service">Послуги</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Teacher">Викладачі</a>
            </li>

            @if(signInManager.IsSignedIn(User) && User.IsInRole(DefaultRoles.Admin))
            { 
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Info">Інформація</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-action="ListRoles" asp-controller="Administration">Ролі</a>
            </li>
            }
        </ul>

        <ul class="navbar-nav ml-auto">
            @if (signInManager.IsSignedIn(User))
            {
                <li class="nav-item">
                    <form method="post" asp-action="logout" asp-controller="account">
                        <button class="nav-link py-0 btn btn-link" type="submit" style="width:auto;">
                            Logout @User.Identity.Name
                        </button>
                    </form>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link" asp-action="Register" asp-controller="Account">Реєстрація</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Login" asp-controller="Account">Війти</a>
                </li>
            }
        </ul>
    </div>
</div>

IISportSchool/Views/Shared/_SectionSummary.cshtml
@model Section

<div class="card card-size card1">
    <img class="card-img-top img-fluid img-responsive" src="@Url.Content(Model.ImagePath)" alt=""/>
    <hr/>
    <div class="card-body">
        <div class="card-title text-center font-weight-bold">@Model.Name</div>
    </div>
    <a asp-action="SectionDetails" asp-route-id="@Model.Id" class="stretched-link"></a>
</div>