IISportSchool/Models/Domain/SchoolService/Group.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IISportSchool.Models
{
    public class Group : SchoolService
    {
        public int MinChildAge { get; set; }
        public int MaxChildAge { get; set; }
        public List<Children> Childrens { get; set; }
        public Section Section { get; set; }
        public int SectionId { get; set; }
        public int PricePerMonth { get; set; }

        public Group(string name, int minChildAge, int maxChildAge, int sectionId, int pricePerMonth)
        {
            Name = name;
            MinChildAge = minChildAge;
            MaxChildAge = maxChildAge;
            SectionId = sectionId;
            PricePerMonth = pricePerMonth;
        }

        public Group()
        {

        }

        public override List<Children> GetAllChildren()
        {
            return Childrens;
        }

        public override int GetNumberOfChildren()
        {
            return Childrens.Count();
        }

        public override double GetServiceProfit()
        {
            return PricePerMonth * GetNumberOfChildren();
        }

        public override List<Worker> GetStaff()
        {
            List<Worker> workers = new List<Worker>();
            return workers;
        }
    }
}

IISportSchool/Controllers/ChildrenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IISportSchool.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IISportSchool.Controllers
{
    public class ChildrenController : Controller
    {
        private IChildrenRepository _repository;
        public ChildrenController(IChildrenRepository repository)
        {
            _repository = repository;
        }

        public IActionResult List()
        {
            return View(_repository.Children);
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult Add(int groupId, string groupName, int minAge, int maxAge)
        {
            AddChildViewModel viewModel = new AddChildViewModel
            {
                Children = new Children { GroupId = groupId },
                MinAge = minAge,
                MaxAge = maxAge
            };
            ViewBag.Group = groupName;
            return View(viewModel);
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpPost]
        public IActionResult Add(AddChildViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            _repository.Add(viewModel.Children);
            return RedirectToAction("Details", "Group", new { id = viewModel.Children.GroupId});
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult Edit(int? id,int groupId, string groupName, int minAge, int maxAge)
        {
            if (id == null || id == 0)
                return BadRequest();

            var child = _repository.GetChildren((int)id);

            if (child == null)
                return NotFound();


            AddChildViewModel viewModel = new AddChildViewModel
            {
                Children = child,
                MinAge = minAge,
                MaxAge = maxAge
            };
            ViewBag.Group = groupName;
            return View(viewModel);
        }

        [Authorize(Roles = DefaultRoles.Admin)]
        [HttpPost]
        public IActionResult Edit(AddChildViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            _repository.Update(viewModel.Children);
            return RedirectToAction("Details", "Group", new { id = viewModel.Children.GroupId });
        }


        [Authorize(Roles = DefaultRoles.Admin)]
        public IActionResult Delete(int? id)
        {
            if (id == null && id == 0)
                return BadRequest();

            var child = _repository.GetChildren((int)id);

            if (child == null)
                return NotFound();

            _repository.Delete(child);

            return RedirectToAction("Details", "Group", new { id = child.GroupId });
        }
    }
}

IISportSchool/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IISportSchool.Models;
using Microsoft.AspNetCore.Authorization;

namespace IISportSchool.Controllers
{
    [Authorize(Roles = DefaultRoles.Admin)]
    public class GroupController : Controller
    {
        IGroupRepository _repository;
        ITeacherRepository _teachers;
        TeacherProxyFactory _teacherProxyFactory;
        public GroupController(IGroupRepository repository, ITeacherRepository teacher, ApplicationDbContext context)
        {
            _repository = repository;
            _teachers = teacher;
            _teacherProxyFactory = new TeacherProxyFactory(context);
        }
        public IActionResult Index()
        {
            var groups = _repository.Groups;
            return View(groups);
        }

        public IActionResult Details(int? id)
        {
            if (id == 0 || id == null)
                return BadRequest();

            var group = _repository.Get((int)id);
            if (group == null)
                return NotFound();
            return View(group);
        }

        public IActionResult Create(int sectionId, string sectionName="")
        {
            var group = new Group { SectionId = sectionId };
            ViewBag.Section = sectionName;
            return View(group);
        }
        [HttpPost]
        public IActionResult Create(Group group)
        {
            if (!ModelState.IsValid)
            {
                return View(group);
            }
            _repository.Add(group);
            _repository.Save();
            return RedirectToAction("SectionDetails", "Service", new { id = group.SectionId });
        }


        public IActionResult Update(int? id)
        {
            if (id == null && id == 0)
                return BadRequest();

            var group = _repository.Get((int)id);
            if (group == null)
                return NotFound();

            return View(group);
        }
        [HttpPost]
        public IActionResult Update(Group group)
        {
            _repository.Update(group);
            _repository.Save();
            return RedirectToAction("UpdateSection", "Service", new { id = group.SectionId });
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return BadRequest();

            var group = _repository.Get((int)id);

            if (group == null)
                return NotFound();

            _repository.Delete(group);
            _repository.Save();

            return RedirectToAction("UpdateSection", "Service", new { id = group.SectionId});
        }
        //[HttpPost]
        //public IActionResult Delete(Group group)
        //{
        //    _repository.Delete(group);
        //    _repository.Save();
        //    return RedirectToAction("Service", "SectionDetails", new { id = group.SectionId });
        //}
    }
}

IISportSchool/Views/Group/Create.cshtml
@model Group

<div class="container">
    <h2>Створення групи для секції "@ViewBag.Section"</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" asp-controller="Group">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="MinChildAge" class="control-label">Мінімальний вік</label>
                    <input asp-for="MinChildAge" class="form-control" />
                    <span asp-validation-for="MinChildAge" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MaxChildAge" class="control-label">Максимальний вік</label>
                    <input asp-for="MaxChildAge" class="form-control" />
                    <span asp-validation-for="MaxChildAge" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PricePerMonth" class="control-label">Ціна за 1 місяць</label>
                    <input asp-for="PricePerMonth" class="form-control" />
                    <span asp-validation-for="PricePerMonth" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Назва групи</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="ImagePath">
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Створити" />
                </div>
                @Html.HiddenFor(g=>g.SectionId)
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IISportSchool/Views/Group/Details.cshtml
@model Group

    <div class="container">
        <h2 class="text-center">@Model.Name группа</h2>
        <h4>Для дітей віком від @Model.MinChildAge до @Model.MaxChildAge років</h4>
        @{
            int childrenNumber = 1;
        }

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>Ім'я</th>
                    <th>Фамілія</th>
                    <th>Вік</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var children in Model.Childrens)
                {
                    <tr>
                        <td>@childrenNumber</td>
                        <td>@children.Name</td>
                        <td>@children.SecondName</td>
                        <td>@children.Age</td>
                        <td width="3%">
                            <a asp-action="Edit" asp-controller="Children"
                               asp-route-id="@children.Id"
                               asp-route-groupId="@Model.Id"
                               asp-route-groupName="@Model.Name"
                               asp-route-minAge="@Model.MinChildAge"
                               asp-route-maxAge="@Model.MaxChildAge"
                               class="btn btn-info">
                                Редагувати
                            </a>
                        </td>
                        <td width="5%"><a class="btn btn-danger" asp-action="Delete" asp-controller="Children" asp-route-id="@children.Id">Видалити</a></td>
                    </tr>

                    childrenNumber++;
                }
            </tbody>
        </table>
    </div>


<div class="container">
    <a asp-action="Add" asp-controller="Children" 
       asp-route-groupId="@Model.Id"
       asp-route-groupName="@Model.Name"
       asp-route-minAge="@Model.MinChildAge"
       asp-route-maxAge="@Model.MaxChildAge"
       class="btn btn-success">
        Додати учня
    </a>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-10">
            <form asp-action="Update" method="post">
                <div class="form-group">
                    <label asp-for="PricePerMonth" class="control-label">Ціна за місяць</label>
                    <input asp-for="PricePerMonth" class="form-control" />
                    <span asp-validation-for="PricePerMonth"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MinChildAge" class="control-label">Мінімальний вік</label>
                    <input asp-for="MinChildAge" class="form-control" />
                    <span asp-validation-for="MinChildAge"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MaxChildAge" class="control-label">Максимальний вік</label>
                    <input asp-for="MaxChildAge" class="form-control" />
                    <span asp-validation-for="MaxChildAge"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Назва</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="PricePerMonth"></span>
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="SectionId" />
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="ImagePath" />
                    <input type="hidden" asp-for="Childrens" />
                </div>
                <button class="btn btn-outline-success" type="submit">Зберегти</button>
            </form>
        </div>
    </div>
</div>

IISportSchool/Views/Group/Index.cshtml
@model IEnumerable<Group>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Номер</th>
                <th>Мін вік</th>
                <th>Макс вік</th>
                <th>Ціна</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var group in Model)
            {
            <tr>
                <td>@group.Name</td>
                <td>@group.MinChildAge</td>
                <td>@group.MaxChildAge</td>
                <td>@group.PricePerMonth</td>
                <td>
                    <a asp-action="Details" asp-controller="Group" asp-route-id="@group.Id"
                       class="btn btn-info">Редагувати</a>
                </td>
                <td>
                    <a asp-action="Delete" asp-controller="Group" asp-route-id="@group.Id"
                       class="btn btn-danger">Видалити</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>